spring:
  application:
    name: kuroline-users-ms
  servlet:
    multipart:
      max-file-size: 3MB
server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: mappings # Expose the /actuator/mappings endpoint to display all HTTP request paths and their handlers

